// Inject the styles (async obvs)
import './reset.amcss!'
import './variables.amcss!'
import './traits/colors.amcss!'
import './traits/typography.amcss!'
import './traits/layout.amcss!'
import './traits/flex.amcss!'
import './traits/flex.tcss!'
import './traits/link.amcss!'
import './core.amcss!'
